### ISSUE TITLE
html sections

### ISSUE THREAD

**Issue by rimmesbe** [lposavad/prj-rev-bwfs-dasmoto#1]
You want to wrap all the elements that should be in the section inside the div including the image, h2, and p tags. That is what divs are for, grouping related elements together.

https://github.com/lposavad/prj-rev-bwfs-dasmoto/blob/master/U2D6DasmotoA%26C/index.html#L12-L19

**Comment by lposavad** [comment]
Done. I moved the </div> tags to the end of their respective information groups, and altered style.css to focus the .brushes, .framing and .paints styles on the h2-/h2 elements.
Another way to do this would be to wrap the previous code in a section-/section, but that may be overkill for this level of webpage.
