### ISSUE TITLE
use class

### ISSUE THREAD

**Issue by rimmesbe** [lposavad/prj-rev-bwfs-dasmoto#4]
This would be a good place to use a class. We don't want to alter the base tags if we don't have to. Using a class here will add some context for the code being styled and we preserve the strong tag for future use elsewhere.
.price { color: blue; }

https://github.com/lposavad/prj-rev-bwfs-dasmoto/blob/master/U2D6DasmotoA%26C/resources/css/style.css#L27-L29

**Comment by lposavad** [comment]
Thanks, I wasn't aware I could add a class qualifier to the strong tag. More reading to be done!
