### ISSUE TITLE
use relative path

### ISSUE THREAD

**Issue by rimmesbe** [lposavad/prj-rev-bwfs-dasmoto#5]
You need to use relative paths for your image files, this path will only work on your computer. The relative path here will be the path from the css file to the image file.
../image.jpg

https://github.com/lposavad/prj-rev-bwfs-dasmoto/blob/master/U2D6DasmotoA%26C/resources/css/style.css#L16

**Comment by lposavad** [comment]
Corrected. Again, thanks!
