### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [lposavad/prj-rev-bwfs-dasmoto#6]
Grade: Satisfactory

Summary: Nice job on the project, looks pretty good. You used some good techniques in here. Take a look at the issues I created as they will help you organize your code better for the upcoming units where we start to position sections. Here are some good tips as well: http://learn.shayhowe.com/html-css/writing-your-best-code/

**Comment by lposavad** [comment]
Thank you! I found your critique very detailed and direct. I appreciate that because it will make me a better coder. Again, thanks!
-Larry Posavad
